# Generated by Django 4.1.1 on 2022-09-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_deepthought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepthought',
            name='deep_thought_text',
        ),
        migrations.AddField(
            model_name='deepthought',
            name='thoughts',
            field=models.TextField(default='Type your deepest thoughts'),
        ),
        migrations.AlterField(
            model_name='deepthought',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
