# Generated by Django 4.1.1 on 2022-09-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_deepthought_deep_thought_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepthought',
            name='thoughts',
            field=models.TextField(default='Type your deepest thoughts...'),
        ),
    ]
