# Generated by Django 4.1.1 on 2022-09-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_deepthought_thoughts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeepThought',
        ),
    ]
